export const Images = {
  welcomeBG: require('./welcomeBG.png'),
  logo: require('./logo.png'),
  searchIcon: require('./searchIcon.png'),
  pointIcon: require('./pointIcon.png'),
  corporateBG: require('./corporateBG.png'),
  camera: require('./camera.png'),
  editIcon: require('./editIcon.png'),
  dateIcon: require('./dateIcon.png'),
  locationIcon: require('./locationIcon.png'),
  rewardIcon: require('./rewardIcon.png'),
  deleteIcon: require('./deleteIcon.png'),
  imagePlaceholder: require('./imagePlaceholder.png'),
  leftArrowBordered: require('./leftArrowBordered.png'),
  rightArrowBordered: require('./rightArrowBordered.png'),
  notfound: require('./notfoundpage.svg'),

  badges: [
    require('./badges/badgeBronze.png'),
    require('./badges/badgeSilver.png'),
    require('./badges/badgeGold.png'),
    require('./badges/badgePlatinum.png'),
    require('./badges/badgeDiamond.png'),
  ],
};
